BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "fligth" (
	"COD_VUELO"	TEXT NOT NULL UNIQUE,
	"HORA_SALIDA"	BLOB NOT NULL,
	"HORA_LLEGADA"	BLOB NOT NULL,
	"PROCEDENCIA"	TEXT NOT NULL,
	"DESTINO"	TEXT NOT NULL,
	"PLAZAS_FUMADOR"	INTEGER NOT NULL,
	"PLAZAS_NO_FUMADOR"	INTEGER NOT NULL,
	"PLAZAS_TURISTA"	INTEGER NOT NULL,
	"PLAZAS_PRIMERA"	INTEGER NOT NULL,
	PRIMARY KEY("COD_VUELO")
);
CREATE TABLE IF NOT EXISTS "passengers" (
	"ID"	TEXT NOT NULL UNIQUE,
	"COD_VUELO"	TEXT NOT NULL,
	"TIPO_PLAZA"	TEXT NOT NULL,
	"FUMADOR"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
COMMIT;
